http://localhost:8080/

###

http://localhost:8080/users/login

###

http://localhost:8080/items/list

###

GET http://localhost:8080/users/login

###

POST http://localhost:8080/users/login
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="first";
usuario=usuH&password=123

###

