http://localhost:8080/

###

http://localhost:8080/users/login

###

http://localhost:8080/items/list

###

GET http://localhost:8080/users/login

###

POST http://localhost:8080/users/login
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="usuario"

"usuH"
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="password"

"123"
--WebAppBoundary--

###
POST http://localhost:8080/users/login
Content-Type: application/x-www-form-urlencoded

usuario=usuH&content=new-element

###